export const LABELS_REQUEST = 'LABELS_REQUEST';
export const LABELS_SUCCESS = 'LABELS_SUCCESS';
export const LABELS_FAILURE = 'LABELS_FAILURE';

export const ADD_LABEL_REQUEST = 'ADD_LABEL_REQUEST';
export const ADD_LABEL_SUCCESS = 'ADD_LABEL_SUCCESS';
export const ADD_LABEL_FAILURE = 'ADD_LABEL_FAILURE';

export const DELETE_LABEL_REQUEST = 'DELETE_LABEL_REQUEST';
export const DELETE_LABEL_SUCCESS = 'DELETE_LABEL_SUCCESS';
export const DELETE_LABEL_FAILURE = 'DELETE_LABEL_FAILURE';

export const TOGGLE_LABLE_ON_GIST_REQUEST = 'TOGGLE_LABLE_ON_GIST_REQUEST';
export const TOGGLE_LABLE_ON_GIST_SUCCESS = 'TOGGLE_LABLE_ON_GIST_SUCCESS';
export const TOGGLE_LABLE_ON_GIST_FAILURE = 'TOGGLE_LABLE_ON_GIST_FAILURE';

export const SELECT_LABEL = 'SELECT_LABEL';
